# Config settings
title: Rowena's MemoryBox
baseurl: "/memorybox3/bb0578c322d10c4ef974d39fd0fc02df43384803/"

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
